service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment:
    redisHost: ${file(../config/${self:provider.stage}.json), 'localhost'}
    redisPort: ${file(../config/${self:provider.stage}.json), '6379'}

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: post
          path: graphql
