service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment:
    redisHost: '${file(./config/${self:provider.stage}.json):redis.host}'
    redisPort: '${file(./config/${self:provider.stage}.json):redis.port}'

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: post
          path: graphql

