service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: 'dev'

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          method: post
          path: graphql
